### ISSUE TITLE
Gorilla Websocket

### ISSUE THREAD

**Issue by niaow** [gofrs/help-requests#1]
* Where is the project currently hosted? https://github.com/gorilla/websocket

* Is the project written only in Go, or does it contain other languages (beyond scripts)? pure go

* Has the project had any recent activity? Last activity June 5. Project still receives bug fixes via pull request.

* Does the project have a maintainer, or a maintainer looking for someone to take
  over the project? Yes. See issue https://github.com/gorilla/websocket/issues/370

* Do you have any example projects that make use of this package? Most go projects with websockets use this package.

* Are there any outstanding **_critical_** bugs that result in the library being
  totally unusable or insecure? Unusure. Fails test suite: https://github.com/gorilla/websocket/issues/368

* Is there anything else you'd like to mention about the project?

**Comment by elithrar** [comment]
The Gorilla organization can create a "team" that includes gofrs members, and grant that team access to the websockets project.

**Comment by jadr2ddude** [comment]
There was also a discussion of possibly mirroring the fork back to the original repo.

**Comment by elithrar** [comment]
I think that becomes pretty complicated, and the "gorilla/websocket" name
is fairly widespread. Solving group permissions is easier than forking,
mirroring and dealing with end-user confusion. Vanity import paths don't
fix this either, and often break.

**Comment by theckman** [comment]
@elithrar I assume some of us would need to become administrators of the `gorilla` organization if we wanted to integrate with any third party applications? These are the types of things I'm not entirely sure of how well they'd work when it comes to taking over a project.

**Comment by theckman** [comment]
If we want to take over, let's not miss this recently closed PR:

- https://github.com/gorilla/websocket/pull/192

**Comment by theckman** [comment]
We're now committed to becoming active in this project. For the time being that'll likely be triaging of issues and reviewing of PRs. As trust is gained with the current maintainers within gorilla it seems likely the responsibility size will grow.

We're committed to keeping the repo at `gorilla/websocket`. That said, in the interest of us being able to collaborate more-easily together, I'm going to fork the project to our organization to be used to issue PRs to `gorilla/websocket`.

**Comment by ptman** [comment]
https://github.com/gofrs/websocket - that is now done. Maybe time to close ticket?
