### ISSUE TITLE
wit.ai Client

### ISSUE THREAD

**Issue by plutov** [gofrs/help-requests#11]
* Where is the project currently hosted?

https://github.com/kurrik/witgo
https://github.com/jsgoecke/go-wit

* Is the project written only in Go, or does it contain other languages (beyond scripts)?

Go only

* Has the project had any recent activity?

Not really, it is not compatible with new Wit.ai API

* Does the project have a maintainer, or a maintainer looking for someone to take
  over the project?

-

* Do you have any example projects that make use of this package?

https://github.com/plutov/packagemain/tree/master/09-slack-bot

**Comment by theckman** [comment]
@plutov thank you for reaching out, and your interest in having us look at taking over these projects. Unfortunately, I don't feel that either of these two projects are a good fit for our organization right now.

We're looking to adopt packages that have reached a certain level of maturity and adoption, that have a sizable impact on the Go ecosystem. Looking at these two packages, and the list of importers for them on `godoc.org`, it doesn't seem like they've had much adoption.

I see that you seem to make use of these clients in your own projects, and so it may make sense for you to look at helping maintain these projects. If the userbase grows, and you need maintainership help, we'd be happy to reevaluate. 👍
