### ISSUE TITLE
Review GitHub Go repositories with stars but old last commit

### ISSUE THREAD

**Issue by plutov** [gofrs/help-requests#14]
Using this GH query I found >40 Go repositories with > 500 stars and which have last commit pushed before Jan 1 ’18.

https://github.com/search?q=language%3Ago+and+stars%3A%3E500+pushed%3A%3C2018-01-01

Something not being pushed doesn't mean it's unmaintained. So we need to manually review those repositories and create help request if necessary.

**Comment by adamdecaf** [comment]
I was writing a script using this metric along with "most importers on godoc.org" to find projects which could use our support the most.

**Comment by theckman** [comment]
It would be rad if someone could go over the data presented here, and to raise any new issues based on the findings. It may be good to note projects you explicitly avoided opening one for, and why (if there is some interesting reason).

@plutov would you be interested in owning that? @adamdecaf or you? Maybe both of you could pair together on this one?

**Comment by plutov** [comment]
@theckman @adamdecaf I am happy to help with this! I did manual review of my query and it doesn't give any potential candidates.

**Comment by adamdecaf** [comment]
I'll finish out my code and generate a list or two.

**Comment by ferhatelmas** [comment]
I had seen this: 

https://isitmaintained.com/ 

might be useful for manual pruning after getting a smaller list.

**Comment by adamdecaf** [comment]
I created https://github.com/gofrs/help-requests/pull/29 for finding both github stars and godoc imports. The script needs sorting (and probably some cleanup), but I wanted to get it pushed up.
