### ISSUE TITLE
fsnotify

### ISSUE THREAD

**Issue by nathany** [gofrs/help-requests#15]
* Where is the project currently hosted?
https://github.com/fsnotify

* Is the project written only in Go, or does it contain other languages (beyond scripts)?
Entirely Go for https://github.com/fsnotify/fsnotify, but related project https://github.com/fsnotify/fsevents uses a fair bit of `cgo` in the Go code.

* Has the project had any recent activity?
Not for several months (Jan 9).

* Does the project have a maintainer, or a maintainer looking for someone to take
  over the project?
Been looking for maintainers for well over a year now: https://github.com/fsnotify/fsnotify/issues/183
(current project owner may still be able to help in some capacity, but has been inactive for some time)

* Are there active projects which replicate the popular functionality of this project?
Related project that is more active: https://github.com/rjeczalik/notify

* Do you have any example projects that make use of this package?
Many many importers: https://godoc.org/github.com/fsnotify/fsnotify?importers

* Are there any outstanding **_critical_** bugs that result in the library being
  totally unusable or insecure?
Possibly. There are many open pull requests and issues.

* Is there anything else you'd like to mention about the project?
I took over this project from @howeyc but have done a poor job of maintaining it as of late. I don't feel like I adequately know the file system APIs (epoll, etc.) to accept/deny pull requests at this time. May be willing to help in some areas now that I have more time available, but the project definitely needs a team if it's going to thrive.

**Comment by nathany** [comment]
I don't believe there has ever been a security audit on fsnotify.

**Comment by nathany** [comment]
Today I was able to do some work on the related fsnotify/fsevents (macOS) project. Anyone planning to be down in Denver for GopherCon this year? A good time to get organized.

**Comment by nathany** [comment]
Ping

**Comment by nathany** [comment]
Hello gophers. Fsnotify could still really use some help. Ideally a couple people for each operating system that it supports.

**Comment by nathany** [comment]
My call for help maintaining fsnotify has had very little result in the past 5 years. 

I will be officially leaving the `fsnotify` project whether or not anyone else picks it up. 

If nobody else takes the project over soon, I will be archiving the project. That way it can still be used as-is but no more issues can be reported. Then it will be up to someone to fork it and maintain it if anyone wants to.

**Comment by nathany** [comment]
Final Notice: Maintainers Wanted 
https://github.com/fsnotify/fsnotify/issues/413

**Comment by ldez** [comment]
fsnotify has found maintainers.
