### ISSUE TITLE
gofrs.github.io

### ISSUE THREAD

**Issue by pedromorgan** [gofrs/help-requests#16]
Can i suggest setting up a www site..

at 
gofrs.github.io

And make it simple bootstrap site (mobile firendly etc)

- that makes the "mission" cleare
-  for other to understand..

ie if its a decent lib and kinda works, then we baby sit..

**Comment by pedromorgan** [comment]
Also set up a gofrs chat channel... on gitter.im

**Comment by adamdecaf** [comment]
@theckman is setting up a site, see https://github.com/gofrs/help-requests/issues/6#issuecomment-412328144

**Comment by theckman** [comment]
I've acquired a domain a few weeks ago, and so I won't be using a `github.io` one. Going to close this only because it's already WIP, and we'll be using a different domain.
