### ISSUE TITLE
https://github.com/istreamdata/orientgo

### ISSUE THREAD

**Issue by bazo** [gofrs/help-requests#18]
* Where is the project currently hosted?

https://github.com/istreamdata/orientgo

* Is the project written only in Go, or does it contain other languages (beyond scripts)?

only go i think

* Has the project had any recent activity?

3 years ago

* Does the project have a maintainer, or a maintainer looking for someone to take
  over the project?

looks abandoned

* Are there active projects which replicate the popular functionality of this project?

i dont think so

* Do you have any example projects that make use of this package?

nope

* Are there any outstanding **_critical_** bugs that result in the library being
  totally unusable or insecure?
 
no support for latest orientdb

* Is there anything else you'd like to mention about the project?

not really

**Comment by zerkms** [comment]
https://godoc.org/gopkg.in/istreamdata/orientgo.v2?importers

**Comment by theckman** [comment]
I did some digging, and it seems like one person who is involved `cayley` used to be involved with this. 

Looking at the lack of known importers for this package, I don't feel this is a good fit for us.
