### ISSUE TITLE
github.com/sirupsen/logrus

### ISSUE THREAD

**Issue by nulladmin** [gofrs/help-requests#2]
* Where is the project currently hosted?
https://github.com/sirupsen/logrus

* Is the project written only in Go, or does it contain other languages (beyond scripts)?

All in Go, widely used.

* Has the project had any recent activity?

Yes

* Does the project have a maintainer, or a maintainer looking for someone to take
  over the project?

Maintainer is looking for someone. From the Readme:

"Are you interested in assisting in maintaining Logrus? Currently I have a lot of obligations, and I am unable to provide Logrus with the maintainership it needs. If you'd like to help, please reach out to me at simon at author's username dot com."

* Do you have any example projects that make use of this package?

From the Godoc: "Package logrus ... is imported by 8024 packages."
Prometheus, Tensorflow, Azure Container Service Engine, etc, etc. The full list is here:

https://godoc.org/github.com/sirupsen/logrus?importers

* Are there any outstanding **_critical_** bugs that result in the library being
  totally unusable or insecure?

Not that I'm aware of. It's actually quite functional and widely used. 

* Is there anything else you'd like to mention about the project?

No affiliation on my part - other then using it in my projects - but if the author needs help then this might be a good candidate for Gofrs help. So consider this a referral.

**Comment by theckman** [comment]
This seems like it could be a good project to help with. I know quite a few projects in the ecosystem use this library, include some of my own personal projects. I can file an issue to ask whether they are still looking, and how they'd like to have us start helping if so.

**Comment by theckman** [comment]
We are still engaged on this one. We figured out how to do the migration in a way that will appease module users, and should be okay for users of things like `dep`. There is one outstanding issue with some of the error messages that the Go toolchain prints when a module is imported using the wrong path, and I'm hoping to get it in to g1.12 so we can more comfortably action the migration:

- https://go-review.googlesource.com/c/go/+/158477

**Comment by ldez** [comment]
logrus is now in maintenance mode, it should be replaced by [slog](https://go.dev/blog/slog) or [zerolog](https://github.com/rs/zerolog), or [zap](https://github.com/uber-go/zap)
