### ISSUE TITLE
GopherCon Role Call

### ISSUE THREAD

**Issue by theckman** [gofrs/help-requests#20]
Hey All,

I planned poorly and didn't think to set up a better medium to see who all from the Gofrs is going to be in Denver this week for GopherCon 2018. I know some will be, including myself. 

If you're in town, and on Slack, please drop a message in the [#gofrs](https://gophers.slack.com/messages/CBP4N9BEU) channel. Include when you come in, and when you leave. If you aren't in the Slack workspace yet you can request an invite [here](https://invite.slack.golangbridge.org/). Also, if you aren't in the [#gophercon-denver](https://gophers.slack.com/messages/C0528UE9X) channel you definitely should be.

If don't wish to join us on Slack, but you're in town, please comment here and let me know a good way to get in contact with you. I'd like to try to meet as many of you as possible. 😄 

Cheers!
-Tim

**Edit:** I'll try to plan better for doing a role call thing next year. I may try to do a community table this year if we have the space. 👍 

CC: @gofrs/all @nathany (although I know you're already gonna be here. 😛)

**Comment by mdlayher** [comment]
I'm here! Looking forward to meeting you! mdlayher on Slack as well.

**Comment by leighmcculloch** [comment]
I'll be there tomorrow onwards! I'm `leigh`on Slack.

**Comment by Xe** [comment]
I'm Xe on slack. I have nothing to do today because I didn't get into a workshop.
