### ISSUE TITLE
Gocode

### ISSUE THREAD

**Issue by gdey** [gofrs/help-requests#25]
* Where is the project currently hosted?

TBD 
* Is the project written only in Go, or does it contain other languages (beyond scripts)?

Yes, may contain other languages. 

* Has the project had any recent activity?

TBD

* Does the project have a maintainer, or a maintainer looking for someone to take
  over the project?

Nate finch is looking for someone to take over

* Are there active projects which replicate the popular functionality of this project?

No

* Do you have any example projects that make use of this package?

* Are there any outstanding **_critical_** bugs that result in the library being
  totally unusable or insecure?

* Please provide a link to the project importers from https://godoc.org. Example: https://godoc.org/github.com/gofrs/uuid?importers

* Is there anything else you'd like to mention about the project?

**Comment by gdey** [comment]
@gdey and @tim talked about this at the bar.

**Comment by jadr2ddude** [comment]
There is an actively maintained fork which nsf/gocode recommends: https://github.com/mdempsky/gocode

**Comment by jadr2ddude** [comment]
If we are willing to help with this, we should ping mdempsky on this issue

**Comment by theckman** [comment]
Is there anyone in the @gofrs/all who feels we should definitely reach out and offer to help, anyone who doesn't? Is there someone who would want to be the "champion", for lack of better terms, for pursuing this project?

**Comment by dylan-bourque** [comment]
I can't think of any specific reason to *not* reach out.  Definitely feels like `gocode` is a widely used tool and the community would be hurt if it withers.  I've also seen quite a few references to people having issues in VS Code recently related to Go 1.11 and `gocode`.  I'd be down to contribute some work, but I definitely don't have the bandwidth to be the steward.

On a little bit of a tangent, I personally like what Sourcegraph is doing with the language server over the plethora of separate command-line tools.

**Comment by mattouille** [comment]
iirc GoCode is the package that's holding up VSCode's support of go modules

**Comment by alecthomas** [comment]
As I understand it, [gopls](https://github.com/golang/go/wiki/gopls) is the officially supported future solution to what gocode provides, so this can probably be closed.
