### ISSUE TITLE
Donation of go-flock

### ISSUE THREAD

**Issue by theckman** [gofrs/help-requests#26]
> Where is the project currently hosted?

https://github.com/theckman/go-flock

> What languages other than Go does the project utilize?

Pure Go, but does have some gnarly Windows system calls.

> When was the project's last activity?

~19 days ago.

> Does the project have a maintainer, or a maintainer looking for someone to take
  over the project?

Yeah. I'm not _actively_ looking, but with it being the most popular flock package (according to imports) it seems good to make sure to maintain it.

> What active projects replicate the popular functionality of this project, if any?

There don't appear to be any direct competitors. Plenty of projects have implemented their own `flock` in subpackages.

> What are some example projects that make use of this package?

https://github.com/theckman/cronner
https://github.com/stripe/veneur 

> Are there any outstanding **_critical_** bugs that result in the library being
  totally unusable or insecure?

Nope, should be pretty stable.

> Please provide a link to the project importers from https://godoc.org. Example: https://godoc.org/github.com/gofrs/uuid?importers

https://godoc.org/github.com/theckman/go-flock?importers

> What else would you like to mention about the project?

**Comment by theckman** [comment]
@gofrs/all Considering my biases, would someone be willing to handle the investigation of this project to see if it's a good fit for us?

**Comment by jadr2ddude** [comment]
So: package is relatively straightforward, and imported by 22 packages. I don't think that this would be too much of a maintenance burden. Here are some things that would need to be done:

1. finish/merge this PR: https://github.com/theckman/go-flock/pull/21
2. review the API and make any possible fixes/simplifications
3. release a v1 for SemVer stability guarantees.

This package is simple and useful.

**Comment by jadr2ddude** [comment]
Repo will be transferred soon. This will also help us see how viable a repo transfer is for gofrs projects.

**Comment by adamdecaf** [comment]
+1 to adopting this project. The code is straightforward enough and self contained.

I updated CI settings a bit: https://github.com/theckman/go-flock/pull/23

Right now `go-flock` is the top result for Go "lock file" queries: https://github.com/search?q=language%3Ago+%22file+lock%22

Fun tidbit: This project was almost added to `dep`: https://github.com/golang/dep/pull/1117

**Comment by theckman** [comment]
I'm on a short vacation this weekend, so it'll likely not happen until early next week (unless I get some spare alone time this weekend).

**Comment by theckman** [comment]
Was hoping PR 21 would get updated so I could merge it before moving the project.

**Comment by theckman** [comment]
Merged. Will migrate now.

**Comment by theckman** [comment]
Done: https://github.com/gofrs/flock
