### ISSUE TITLE
github.com/samuel/go-zookeeper

### ISSUE THREAD

**Issue by nemith** [gofrs/help-requests#28]
* Where is the project currently hosted?
github.com/samuel/go-zookeeper

* What languages other than Go does the project utilize?
Pure Go

* When was the project's last activity?
Jan 30th, 2018.  However there are 56 active issues and 23 PRs dating back to 2013.  I have had pull requests accepted in the past year, but it is spotty at best.

* Does the project have a maintainer, or a maintainer looking for someone to take
  over the project?
@samuel is the owner of the repo and does some maintenance.  However I haven't been able to contact him recently.

* What active projects replicate the popular functionality of this project, if any?
None

* What are some example projects that make use of this package?
There are not many public project that use this library as it requires a full apache zookeeper infrastructure which is hard to setup for a open source project.  However it is used in many corporations to access zk infra.

Some public repos i have found:
github.com/youtube/vitess/
github.com/sendgrid/go-solr

Browsing through just OSS on github there is Comcast, Cisco

* Are there any outstanding **_critical_** bugs that result in the library being
  totally unusable or insecure?

We have been running into a number of bugs around leaked goroutines after a Close() call,  some data races, but overall the library doesn't have critical bugs.

* Please provide a link to the project importers from https://godoc.org. Example: https://godoc.org/github.com/gofrs/uuid?importers

https://godoc.org/github.com/samuel/go-zookeeper/zk?importers

* What else would you like to mention about the project?

**Comment by adamdecaf** [comment]
+1 to adoption. This is used in [vault](https://github.com/hashicorp/vault/blob/master/physical/zookeeper/zookeeper.go) and [prometheus](https://github.com/prometheus/prometheus/blob/master/discovery/zookeeper/zookeeper.go) and there are tons of importers. 

I've worked with this library a bit, but will help out on the issues PR's. 

There seems to be another fork [from the network graph](https://github.com/samuel/go-zookeeper/network). Should we talk to mesosphere?  

https://github.com/mesosphere/go-zookeeper

**Comment by adamdecaf** [comment]
I emailed samuel.

**Comment by nemith** [comment]
> I emailed samuel.

I did as well a little over a month ago and got no response.

**Comment by adamdecaf** [comment]
I haven't heard anything.

**Comment by nemith** [comment]
Any plan here?  Anything I can help out with?

**Comment by adamdecaf** [comment]
Dunno. The issues have been pretty quiet.

**Comment by alxn** [comment]
We have heavy use of this library at Uber and had a couple of PR's merged previously (https://github.com/samuel/go-zookeeper/pull/134, https://github.com/samuel/go-zookeeper/pull/126),  we'd like to try and get more things merged (https://github.com/samuel/go-zookeeper/issues/204).

There's a few other wrappers around this library that we could contribute back too (a fake Zookeeper implementation for testing).

I think it would be a good idea to talk to mesosphere (@jdef).

**Comment by ldez** [comment]
The original repo has been archived and replaced by https://github.com/go-zookeeper/zk.

So I closed this issue.
