### ISSUE TITLE
github.com/spf13/viper

### ISSUE THREAD

**Issue by caalberts** [gofrs/help-requests#31]
Where is the project currently hosted?

https://github.com/spf13/viper

When was the project's last activity?

Latest commit on 18 Apr 2017
Ongoing issues and unmerged PRs

Does the project have a maintainer, or a maintainer looking for someone to take over the project?

No response from the maintainer on issues and PRs.

What active projects replicate the popular functionality of this project, if any?

https://github.com/micro/go-config
https://github.com/joho/godotenv
These aim to solve the same problem of application configuration, but neither are as full featured as viper

What are some example projects that make use of this package?
From https://godoc.org/github.com/spf13/viper?importers:
- hugo
- jaegertracing

Are there any outstanding **_critical_** bugs that result in the library being totally unusable or insecure?

not at this time
 

Please provide a link to the project importers from https://godoc.org.

 https://godoc.org/github.com/spf13/viper?importers

**Comment by adamdecaf** [comment]
Scanning the first page of issues there seems to be a lot of bugs open.

**Comment by theckman** [comment]
@adamdecaf so back at GopherCon there was some talk of there being an opportunity to look in to these packages too. There may be some people who have some access to the repo, and could start a conversation around helping out. There are two other packages that are pretty closely related to `viper`: `spf13/cobra` and `spf13/pflag`, and we may need to understand whether we should look at those too.

**Comment by ldez** [comment]
viper has maintainers now, so I closed this issue.
