### ISSUE TITLE
bitly/oauth2_proxy

### ISSUE THREAD

**Issue by adamdecaf** [gofrs/help-requests#32]
**Where is the project currently hosted?**

https://github.com/bitly/oauth2_proxy

**What languages other than Go does the project utilize?**

There are a couple bash files for deploy/testing. 

**When was the project's last activity?**

Commit: March 24, 2018
Release: April 24, 2017

**Does the project have a maintainer, or a maintainer looking for someone to take over the project?**

Not really, but there's been activity to try and [find a new maintainer](https://github.com/bitly/oauth2_proxy/issues/628#issuecomment-445132720) (or Github Org). 

**What active projects replicate the popular functionality of this project, if any?**

[buzzfeed/sso](https://github.com/buzzfeed/sso) supports the same high-level idea, but implemented and configured differently. It's non trivial to switch. 

**What are some example projects that make use of this package?**

Lots of companies use this and have it running. It's used widely in Kubernetes shops. 

**Are there any outstanding **_critical_** bugs that result in the library being totally unusable or insecure?**

I'm not aware of any open critical issues, but there are a lot to sift through. The project could use a re-read and modern linter and CI. 

**What else would you like to mention about the project?**

9 people (myself makes 10) who have commented on the [maintainer issue](https://github.com/bitly/oauth2_proxy/issues/628) in the past two weeks. There are lots of people still using this.

**Comment by adamdecaf** [comment]
I'll volunteer some time to re-read, spruce up CI, and run through issues if we adopt the project. I'd like to see it be maintained at least.

**Comment by theckman** [comment]
@adamdecaf considering https://github.com/bitly/oauth2_proxy/pull/684 should we still consider this?

**Comment by adamdecaf** [comment]
Yea.
