### ISSUE TITLE
github.com/golang/dep

### ISSUE THREAD

**Issue by niaow** [gofrs/help-requests#33]
Where is the project currently hosted?

> https://github.com/golang/dep
> 

What languages other than Go does the project utilize?

> `bash` for an installation script
> 

When was the project's last activity?

> Oct 3, 2018 (last commit)
> 

Does the project have a maintainer, or a maintainer looking for someone to take over the project?

> Project has not been actively maintained since Go Modules were released as the official experiment.
> 

Are there any outstanding **_critical_** bugs that result in the library being totally unusable or insecure?

> Module awareness is not available in the current version of dep. This can result in conflicting import paths between dep and mod.
>

**Comment by theckman** [comment]
Seems if we want to do this we'll need to pursue a hard fork.

**Comment by ldez** [comment]
Dep is replaced by go modules, so I closed this issue.
