### ISSUE TITLE
github.com/benbjohnson/clock

### ISSUE THREAD

**Issue by theckman** [gofrs/help-requests#35]
>Where is the project currently hosted?

* https://github.com/benbjohnson/clock

With subsequent forks:

* https://github.com/facebookgo/clock
* https://github.com/andres-erbsen/clock

>What languages other than Go does the project utilize?

None.

>When was the project's last activity?

* `github.com/benbjohnson/clock`: 2016/12/16
* `github.com/facebookgo/clock`: 2015/04/09
* `github.com/andres-erbsen/clock`: 2016/05/26

>Does the project have a maintainer, or a maintainer looking for someone to take over the project?

All of the listed repos have a lack of activity, and some outstanding issues / PRs. There is no visible request for assistance.

>What active projects replicate the popular functionality of this project, if any?

* https://github.com/mixer/clock (unusual API design)
* https://github.com/efritz/glock (missing parts of API)

>What are some example projects that make use of this package?

* Some projects under https://github.com/cockroachdb
* https://github.com/uber/kraken
* https://github.com/vimeo/statsdaemon
* https://github.com/buzzfeed/sso
* https://github.com/spiffe/spire ([spiffe/spire#797](https://github.com/spiffe/spire/issues/797))

>Are there any outstanding **_critical_** bugs that result in the library being totally unusable or insecure?

Yes, each project has its share of bugs. Some ones to note:

* https://github.com/benbjohnson/clock/issues/4
* https://github.com/benbjohnson/clock/issues/8
* https://github.com/benbjohnson/clock/issues/9
* https://github.com/facebookgo/clock/pull/3
* https://github.com/andres-erbsen/clock/pull/2

>Please provide a link to the project importers from https://godoc.org.

* https://godoc.org/github.com/benbjohnson/clock?importers
* https://godoc.org/github.com/facebookgo/clock?importers
* https://godoc.org/github.com/andres-erbsen/clock?importers

>What else would you like to mention about the project?

It seems like a small API that offers an interesting solution to a problem quite a few may need to solve. I've ran in to similar pains with testing, and would have definitely tried to see if this package made my tests easier to manage.

There was a small Slack conversation about this starting here: https://gophers.slack.com/archives/CBP4N9BEU/p1552522641030300

**Comment by ldez** [comment]
The most active fork seems now to be https://github.com/itbasis/go-clock.
