### ISSUE TITLE
asaskevich/govalidator

### ISSUE THREAD

**Issue by tariq1890** [gofrs/help-requests#36]
Where is the project currently hosted?

> https://github.com/asaskevich/govalidator
>  

When was the project's last activity?

> Jul 20, 2018
> 

Does the project have a maintainer, or a maintainer looking for someone to take over the project?

> No
> 

What active projects replicate the popular functionality of this project, if any?

> None that I know of.

Are there any outstanding **_critical_** bugs that result in the library being totally unusable or insecure?

> https://github.com/asaskevich/govalidator/issues/266. While the fix has been merged into master for this. A release hasn't yet been cut.

**Comment by theckman** [comment]
Speaking personally, :-1:. Whenever I see this mentioned in the community, I advocate for avoiding it and to instead write a purpose-built validation function. It's a complex dependency that utilizes reflection. Adopting this in to your project increases the cognitive burden, as you and any contributors now need to learn how it works and the nuances of that. A function you write and test is much more clear and approachable.

How do other Gofrs feel?

**Comment by adamdecaf** [comment]
I don't think we should adopt this project. As Tim said reflection is hidden underneath and the functions may not be completely correct for any given business case. 

The [ISO 3166](https://github.com/asaskevich/govalidator/blame/f9ffefc3facfbe0caee3fea233cbb6e8208f4541/types.go#L161) and [ISO 4217](https://github.com/asaskevich/govalidator/blame/f9ffefc3facfbe0caee3fea233cbb6e8208f4541/types.go#L414) codes haven't been updated for several years.
