### ISSUE TITLE
johnboulle/clockwork

### ISSUE THREAD

**Issue by joeblubaugh** [gofrs/help-requests#37]
Where is the project currently hosted?
> https://github.com/jonboulle/clockwork

What languages other than Go does the project utilize?
> only Go

When was the project's last activity?
> Jan 4 2019 - last merged PR 

Does the project have a maintainer, or a maintainer looking for someone to take over the project?
> The current maintainer has been inactive since January

What active projects replicate the popular functionality of this project, if any?
> There's github.com/benbjohnson/clock but it's also unmaintained and buggy (see #35)

What are some example projects that make use of this package?

> `kubectl` uses it in several packages. coreOS uses this in several packages. etcd uses this in several packages.

Are there any outstanding **_critical_** bugs that result in the library being totally unusable or insecure?

> There's no time.Timer support in the package, and issues about it have been open for years.

Please provide a link to the project importers from https://godoc.org.

> https://godoc.org/github.com/jonboulle/clockwork?importers

What else would you like to mention about the project?

> This package has many, many more importers than benbjohnson/clock and seems similarly unmaintained and incomplete.

**Comment by cristaloleg** [comment]
404 ?

**Comment by adamdecaf** [comment]
The link looks to be https://github.com/jonboulle/clockwork

**Comment by ldez** [comment]
It feels like https://github.com/jonboulle/clockwork has been "replaced" by https://github.com/benbjohnson/clock.

But https://github.com/benbjohnson/clock is now archived too.
The more active fork seems to be https://github.com/itbasis/go-clock.
