### ISSUE TITLE
github.com/guregu/null

### ISSUE THREAD

**Issue by bharath23** [gofrs/help-requests#39]
Where is the project currently hosted?

> https://github.com/guregu/null

What languages other than Go does the project utilize?

> N/A

When was the project's last activity?

> August 1, 2018 

Does the project have a maintainer, or a maintainer looking for someone to take over the project?

> https://github.com/guregu

What active projects replicate the popular functionality of this project, if any?

> There's github.com/baz/bar but it's really incomplete.
> There's also github.com/quz/bar but it's also unmaintained.

What are some example projects that make use of this package?

> None that I could find

Are there any outstanding **_critical_** bugs that result in the library being totally unusable or insecure?

> Merging https://github.com/guregu/null/pull/36 and https://github.com/guregu/null/issues/47

Please provide a link to the project importers from https://godoc.org.

> Numerous
> https://pkg.go.dev/gopkg.in/guregu/null.v3?tab=importedby
>

What else would you like to mention about the project?

> It is an important project to use when you want to use null types in SQL or JSON.

**Comment by guregu** [comment]
I've taken care of those issues and released v4. Unless some bugs surface, the package should be essentially complete now.

**Comment by bharath23** [comment]
Thanks for making a new release.
