### ISSUE TITLE
add "are there alternatives available" to PR template

### ISSUE THREAD

**Issue by adamdecaf** [gofrs/help-requests#4]
I propose we add the following to the PR template questions: 

`Are there active projects which replicate the popular functionality of this project?`

Currently the following questions are asked:

* Where is the project currently hosted?
* Is the project written only in Go, or does it contain other languages (beyond scripts)?
* Has the project had any recent activity?
* Does the project have a maintainer, or a maintainer looking for someone to take
  over the project?
* Do you have any example projects that make use of this package?
* Are there any outstanding **_critical_** bugs that result in the library being
  totally unusable or insecure?
* Is there anything else you'd like to mention about the project?

**Comment by theckman** [comment]
@adamdecaf would you be willing to raise a PR against this file? https://github.com/gofrs/help-requests/blob/master/.github/ISSUE_TEMPLATE

**Comment by adamdecaf** [comment]
For sure!
