### ISSUE TITLE
github.com/bmaupin/go-epub

### ISSUE THREAD

**Issue by bmaupin** [gofrs/help-requests#40]
Where is the project currently hosted?

> https://github.com/bmaupin/go-epub
> 

What languages other than Go does the project utilize?

> none
> 

When was the project's last activity?

> Aug 19, 2019
> 

Does the project have a maintainer, or a maintainer looking for someone to take over the project?

> I'm the original creator and current owner/maintainer, but I no longer have the time/interest to maintain this by myself. There are a few open issues/PRs that I haven't had the time to look into. I would love to transfer it into loving hands :)
> 

What active projects replicate the popular functionality of this project, if any?

> None that I'm aware of (that are actively maintained)
> This package is the top result for `epub`: https://pkg.go.dev/search?q=epub

What are some example projects that make use of this package?

> I have an example project here: https://github.com/bmaupin/go-docs-epub
> 

Are there any outstanding **_critical_** bugs that result in the library being totally unusable or insecure?

> Not that I'm aware of
> 

Please provide a link to the project importers from https://godoc.org.

> https://pkg.go.dev/github.com/bmaupin/go-epub?tab=importedby

What else would you like to mention about the project?

> The public API is fully documented
> 87% test coverage (nearly all of the reachable code)

**Comment by ldez** [comment]
Hello,

I'm sorry you didn't receive feedback from gofrs (I'm a recent new member)

I see that you have found a solution https://github.com/bmaupin/go-epub/issues/68

The "official" fork is https://github.com/go-shiori/go-epub.
