### ISSUE TITLE
enumer

### ISSUE THREAD

**Issue by ptman** [gofrs/help-requests#42]
Where is the project currently hosted?

> https://github.com/alvaroloes/enumer
> or a fork like 
> https://github.com/noho-digital/enumer

What languages other than Go does the project utilize?

> none
> 

When was the project's last activity?

> 2019-09-02
> 

Does the project have a maintainer, or a maintainer looking for someone to take over the project?

> The current maintainer doesn't seem active
> 

What active projects replicate the popular functionality of this project, if any?

> There are several forks

What are some example projects that make use of this package?

> There are several forks

Are there any outstanding **_critical_** bugs that result in the library being totally unusable or insecure?

> https://github.com/alvaroloes/enumer/issues/65

Please provide a link to the project importers from https://godoc.org.

> https://pkg.go.dev/github.com/alvaroloes/enumer?tab=importedby

What else would you like to mention about the project?

> This seems to be the most popular enumer project, but there are others

**Comment by adamdecaf** [comment]
It seems like there are a lot of forks, so there may be one that's better to use. https://github.com/alvaroloes/enumer/network
