### ISSUE TITLE
Godef

### ISSUE THREAD

**Issue by antham** [gofrs/help-requests#8]
* Where is the project currently hosted?

https://github.com/rogpeppe/godef

* Is the project written only in Go, or does it contain other languages (beyond scripts)?

Yes

* Has the project had any recent activity?

Last commit in main branch was done 11 months ago

* Does the project have a maintainer, or a maintainer looking for someone to take
  over the project?

There is no official request to take the project over, the maintainer is rogpeppe

* Do you have any example projects that make use of this package?

=> https://github.com/microsoft/vscode-go
=> https://github.com/dominikh/go-mode.el
=> https://github.com/fatih/vim-go

* Are there any outstanding **_critical_** bugs that result in the library being
  totally unusable or insecure?

I don't know, it seems to mostly work.

* Is there anything else you'd like to mention about the project?

This project is quite essential as a part of go tooling.

**Comment by Asarew** [comment]
See also my comment in one of the stale [issues](https://github.com/rogpeppe/godef/pull/77#issuecomment-400823178).

**Comment by antham** [comment]
Ah ok, I saw your comment but I didn't know you where from this organization

**Comment by theckman** [comment]
Pinged again. If we don't hear back relatively soon (day or two) I'll bring up the repository.
